name: Add New Profile or Change Profile
description: Create a new profile or change data of an existing profile
title: "Create Profile for ..."
labels: [Profile]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out some informations about you! Great to have you as part of the #ASK network! Your data will be published on the LEAD website. 
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "Your full name."
    validations:
      required: true  

  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload an image for your profile by dragging & dropping into this textarea or clicking on the bottom of this textarea and select your image. 
    validations:
      required: true

  - type: input
    id: country
    attributes:
      label: Country
      description: "In which country are you active?"
      placeholder: "e.g. South Sudan"
    validations:
      required: true
      
  - type: input
    id: region
    attributes:
      label: Region
      description: |
        In which region are you active?

        **Regions in Uganda:** (choose one from the list if you are in Uganda)
        West Nile, Acholi, Karamoja, Western, Lango, Teso, Elgon, South Western, Central, East Central

        **Regions in South Sudan:** (choose one from the list if you are in South Sudan)
        Northern Bahr el Ghazal, Western Bahr el Ghazal, Lakes, Warrap, Western Equatoria, Central Equatoria, Eastern Equatoria, Jonglei, Unity, Upper Nile
      placeholder: "e.g. West Nile"
    validations:
      required: true

  - type: input
    id: hub
    attributes:
      label: Organisation
      description: "If you are active in an organisation/hub, you can indicate here in which."
      placeholder: "Organisation/Hub Name"
    validations:
      required: false

  - type: input
    id: languages
    attributes:
      label: Languages
      description: "Please state which languages you speak (and at what level)"
      placeholder: "e.g. English (very good)"
    validations:
      required: false

################# Skills #################

  - type: markdown
    attributes:
      value: |
        ## Skills 
        What are your skills? Please just fill out your four main skills (or less). You can mention more in your profile text below. 
        
        Examples: 
        - **Web & Software** — e.g. research, using platforms, basic social media experience, installing and using programs, basic coding skills
        - **Hardware & Repair** — e.g. experience with electronics or mechanical devices, managing repair cafes, how to fix anything
        - **Community & Moderation** — e.g. connecting people, event facilitation, activism, trauma healing, gender equality awareness, mediation
        - **Organizational Development** — e.g. entrepreneurship, project management, leading associations, financial literacy
        - **Media & Art** — e.g. audio/video/graphics skills, poetry, music, podcasts, design, STEAM
        - **Data Security & Research** — e.g. data analysis, data sovereignty, privacy, encryption, protection of personal data
        - **Open Source & Knowledge** — e.g. git, open source philosophy, open source licenses, open access, knowledge sharing
        - **Sustainability & Environment** — e.g. SDGs, circular economy, environmental protection, upcycling & recycling
        - **Production & Supply** — e.g. agriculture, animal farming, (re)producing goods and market-items, manufacturing business/service, logistics and physical goods management

  - type: dropdown
    attributes:
      label: Skill 1
      description: "Which skill? You should choose at least one. "
      multiple: false
      options: 
        - Web & Software
        - Hardware & Repair
        - Community & Moderation
        - Organizational Development
        - Media & Art
        - Data Security & Research
        - Open Source & Knowledge
        - Sustainability & Environment
        - Production & Supply
    validations:
      required: false

  - type: textarea
    id: skill1
    attributes:
      label: Qualifications for Skill 1
      description: |
        For each skill please enter some qualifications, so others can verify what experience you have. That can be: 

        - a **degree** or a **certificate** (no need to upload, just type what it is)
        - information about a **prototype / product** you've created (can be a podcast, a video, a device you've built, or some other work you did). You can include links to other websites. 
        - information about a **workshop / training** you've conducted
        - a **recommendation** of an #ASKnet member or a former employer
        - any **other website** where you and your skill is mentioned

    validations:
      required: false

  - type: dropdown
    attributes:
      label: Skill 2
      description: "Which skill? Leave empty if doesn't apply. "
      multiple: false
      options: 
        - Web & Software
        - Hardware & Repair
        - Community & Moderation
        - Organizational Development
        - Media & Art
        - Data Security & Research
        - Open Source & Knowledge
        - Sustainability & Environment
        - Production & Supply
    validations:
      required: false

  - type: textarea
    id: skill2
    attributes:
      label: Qualifications for Skill 2
      placeholder: leave empty if this doesn't apply to you      
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Skill 3
      description: "Which skill? Leave empty if doesn't apply. "
      multiple: false
      options: 
        - Web & Software
        - Hardware & Repair
        - Community & Moderation
        - Organizational Development
        - Media & Art
        - Data Security & Research
        - Open Source & Knowledge
        - Sustainability & Environment
        - Production & Supply
    validations:
      required: false

  - type: textarea
    id: skill3
    attributes:
      label: Qualifications for Skill 3
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Skill 4
      description: "Which skill? Leave empty if doesn't apply. "
      multiple: false
      options: 
        - Web & Software
        - Hardware & Repair
        - Community & Moderation
        - Organizational Development
        - Media & Art
        - Data Security & Research
        - Open Source & Knowledge
        - Sustainability & Environment
        - Production & Supply
    validations:
      required: false

  - type: textarea
    id: skill4
    attributes:
      label: Qualifications for Skill 4
      placeholder: leave empty if this doesn't apply to you
    validations:
      required: false

################## Description Text ###################

  - type: markdown
    attributes:
      value: |
        ## Profile Text 

  - type: textarea
    id: description
    attributes:
      label: "describe yourself"
      description: Tell others about yourself, your story, your expertise in some short sentences or some paragraphs.
    validations:
      required: true

################## Contact ###################

  - type: markdown
    attributes:
      value: |
        ## Contact 
        
        How and where do you want to be contacted? Fill in your contact details, and leave the fields that you don't use blank. We'd kindly ask to give at least one contact option. 
        
        **Please be aware that this information will be publicly visible on the internet! Just fill in those fields that you are okay with to be public.**
        
  - type: input
    id: email
    attributes:
      label: E-Mail
      placeholder: "your E-Mail address"
    validations:
      required: false
  - type: input
    id: tel
    attributes:
      label: Phone
      description: "**Important: If you input your phone number, it will be visible on your LEAD profile and therefore for everyone on the internet! Just enter your number if you are okay with that,** otherwise leave the field empty."
      placeholder: "your phone number, e.g. +254 12 345 6789"
    validations:
      required: false
  - type: input
    id: whatsapp
    attributes:
      label: WhatsApp
      description: "**Important: If you input your phone number, it will be visible on your LEAD profile and therefore for everyone on the internet! Just enter your number if you are okay with that,** otherwise leave the field empty."
      placeholder: "your whatsapp phone number, e.g. +254 12 345 6789"
    validations:
      required: false
  - type: input
    id: website
    attributes:
      label: Website
      placeholder: "your homepage, e.g. https://www.yourwebsite.com"
    validations:
      required: false
  - type: input
    id: telegram
    attributes:
      label: Telegram
      placeholder: "your telegram username"
    validations:
      required: false
  - type: input
    id: github
    attributes:
      label: GitHub
      placeholder: "your github username"
    validations:
      required: false
  - type: input
    id: linkedin
    attributes:
      label: LinkedIn
      placeholder: "URL to your LinkedIn Profile"
    validations:
      required: false
  - type: input
    id: twitter
    attributes:
      label: Twitter
      placeholder: "your twitter username"
    validations:
      required: false
  - type: input
    id: facebook
    attributes:
      label: Facebook
      placeholder: "your facebook username"
    validations:
      required: false
  - type: input
    id: instagram
    attributes:
      label: Instagram
      placeholder: "your instagram username"
    validations:
      required: false
  - type: input
    id: mastodon
    attributes:
      label: Mastodon
      placeholder: "your mastodon profile link"
    validations:
      required: false
  - type: input
    id: wikifab
    attributes:
      label: WikiFab
      placeholder: "your wikifab username"
    validations:
      required: false
  - type: input
    id: other
    attributes:
      label: Other
      description: "If you prefer another way of being contacted, you can state it here. "
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### You've made it! 

        Submit your profile by pressing "Submit new issue" down below (you may need to scroll a bit further). 



